import { Course } from "@/services/db";
export const dummyCourses: Course[] = [
  {
    id: "1",
    title: "Introduction to Computer Science",
    code: "CS101",
    professor: "Dr. Alan Turing",
    color: "#3b82f6",
    credits: 4,
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: "2",
    title: "Data Structures & Algorithms",
    code: "CS202",
    professor: "Dr. Ada Lovelace",
    color: "#10b981",
    credits: 3,
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: "3",
    title: "Linear Algebra",
    code: "MATH221",
    professor: "Dr. Gilbert Strang",
    color: "#8b5cf6",
    credits: 4,
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: "4",
    title: "Database Management Systems",
    code: "CS311",
    professor: "Dr. Edgar Codd",
    color: "#f59e0b",
    credits: 3,
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: "5",
    title: "Operating Systems",
    code: "CS350",
    professor: "Dr. Linus Torvalds",
    color: "#ef4444",
    credits: 4,
    createdOn: new Date(),
    updatedOn: new Date(),
  },
  {
    id: "6",
    title: "Artificial Intelligence",
    code: "CS480",
    professor: "Dr. Geoffrey Hinton",
    color: "#ec4899",
    credits: 3,
    createdOn: new Date(),
    updatedOn: new Date(),
  },
];